spring:
  application:
    name: currency-converter
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      refresh:
        enable: false
server:  port: 8081